### ISSUE TITLE
Add Flair API to HASSIO?

### ISSUE THREAD

**Issue by tinso** [ttolttol2/hass-flair-puck#1]
Do you know how to do it? Cant follow the instructions on the link provided since the HASSIO shell is limited. Any guidance or pointing me on the right direction would be very appreciated.

Thanks

**Comment by ttolttol2** [comment]
I don't know exactly what is your problem. but we can start with this link :)
https://community.home-assistant.io/t/how-to-install-using-pip-on-hass-io/100952
